spring:
  datasource:
    url: jdbc:mysql://192.168.8.8:3306/test?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 4123
    driver-class-name: com.mysql.cj.jdbc.Driver